# AIGenApp Configuration

bizdefs_dir: "bizdefs"
app_extensions_dir: "app-extensions"
www_root: "wwwroot"
database_dsn: "aigen.db"
domain: ""
port: "5000"
agentic_config_path: "agentic.yaml"
custom_ui_path: "/home/innomon/orez/apps/startup-ecosys/custom_ui"
